apiVersion: v1
kind: Service
metadata:
  name: {{ required "Name of service is required" .Values.service.name }}-canary
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ required "Name of service is required" .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
{{- with required "SelectorCanaryLabels for service is required" .Values.service.selectorCanaryLabels }}
  selector:
{{ toYaml . | indent 4 }}
{{- end }}
